# Generated by Django 3.2.13 on 2022-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_pw', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_tel', models.CharField(max_length=255)),
            ],
        ),
    ]
